apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "krakend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "krakend.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "krakend.fullname" . }}-configmap
        {{- if .Values.addlVolumes }}
        {{- toYaml .Values.addlVolumes | nindent 8 }}
        {{- end }}
        - name: jwt
          secret:
            secretName: jwt
            items:
            - key: jwt.json
              path: jwt.json
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/krakend/krakend.json
              subPath: krakend.json
            {{- if .Values.addlVolumeMounts }}
            {{- toYaml .Values.addlVolumeMounts | nindent 12 }}
            {{- end }}
            - name: jwt
              mountPath: /etc/krakend/jwt.json
              subPath: jwt.json
              readOnly: true
          env:
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/__health"
              port: http
          readinessProbe:
            httpGet:
              path: "/__health"
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
